[project]
name = "hwtypes"
version = "1.5.0"
description = "Python implementations of fixed size hardware types (Bit, BitVector, UInt, SInt, ...) based on the SMT-LIB2 semantics"
readme = "README.md"
requires-python = ">=3.6"
authors = [{ name = "Leonard Truong", email = "lenny@cs.stanford.edu" }]
dependencies = ["pysmt", "z3-solver", "gmpy2"]

[tool.setuptools]
packages = ["hwtypes"]
